### ISSUE TITLE
LibreSpot not maintained

### ISSUE THREAD

**Issue by arjenpdevries** [balbuze/volumio-plugins#117]
Diving into new options for using spotify in Volumio, I noticed that LibRespot is currently not maintained...

https://github.com/plietar/librespot/commit/171be66fd959b956a8aab58e886cdc986ab4b4a4

How does that impact project `volspotconnect2`?

**Comment by balbuze** [comment]
Hi,
Yes, librespot is currently unmaintened. Plenty of forks provide miscellanous new features/bug correction. I try to agregate them, when I see a advantage for the plugin... I hope a lead fork will appears in order to keep this wonderful project.
Waiting, I uploaded a exeperimental version, with a initial volume setting, more meatadata(not used yet in web UI). Feel free to test https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect-futurdev
