### ISSUE TITLE
Volumio disconnects from Spotify Connect

### ISSUE THREAD

**Issue by rickhlx** [balbuze/volumio-plugins#152]
After installing the plugin Volumio appears on Spotify Connect. However after a while of not using it, it will disconnect and not able to see it until I disable/enable the plugin.

**Comment by kayue** [comment]
It happens to me from time to time. 

I thought it was my Pi's wifi not stable, disconnect all the time.

**Comment by ashthespy** [comment]
Yes, this is a current limitation of the underlying librespot library we use - it doesn't handle disruptions form the network well.
As a side note, I have also noticed off late that this seems to be happening more frequently - I initially put it down to bad internet at work, but I will look into this in more detail. 👀

**Comment by ibikingi** [comment]
Same problem here, been that way for at least 2 weeks. After reconnecting usually works normally, but after playing a song, phone's Spotify thinks that it has stopped playing at the end of that first song (progress bar stuck and sometimes thinks its paused). Even though volume control and pressing next/previous works, the album art is wrong.
Would actually be bearable if it would allow disconnecting from Volumio, now Spotify doesn't allow changing the output device (back to phone) because it thinks music is paused. Killing Spotify process on phone doesn't really help and that pretty much means music won't stop playing before killing the process on Volumio's end. At this point the control bar is gone but somehow clicking on songs starts playing them on the Pi. On a more positive note Volumio's UI seems to work better now than before.
My Pi has been rocking this plugin for months now and it has worked flawlessly until now, thus I applaud the people who made this plugin possible and have the enthusiasm to keep working on it to enable us all the best possible Spotify experience.
THANK YOU!

**Comment by balbuze** [comment]
yes we known all these problems... We are working to solve it but must admit we struggle... Sorry for inconvenience

**Comment by ayhlai** [comment]
Not sure if its the same issue,  What I noticed using the latest master is that is that the queue of spotify phone app and volspotconnect2 goes out sync very easily.  

Reproduce:
1. Play a spotify playlist from phone on volumio
2. After 10mins or so,  the phone will show the wrong song compared to volumio. 
3. Phone can skip next , but still showing wrong song
4. On positive side,  volumio can also skip song.

Thanks for all the effort!!

**Comment by ashthespy** [comment]
@ayhlai see #145

**Comment by nanomesher** [comment]
Oh yes. thanks! just found out it's Android specific issue.  ios and windows is working perfectly. thanks.
