### ISSUE TITLE
stop volumio when spotify starts playing.

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#16]
Love your work, but I'd love to see that volumio stops playing when spotify con starts.
Maybe something as discribed in this link would work?https://github.com/badaix/snapcast/issues/65

I'm nog a coder myself but i think this might work.

Many thanks
Dennis

**Comment by balbuze** [comment]
Thanks for thé link. This something I started to think, and it will be useful ! There several points on which I'm working...

**Comment by balbuze** [comment]
I added a volumio stop in volspotconnect2. It works but it takes a least 7 sec before starting playing spotify.
If you test you will see two device. It's because allowing several user on the same device. Due to librespot actual limitation I had to do this (dirty) workaround, but it's doing the job...

**Comment by cortegedusage** [comment]
Actually I did the same with librespot and Moodeaudio this weekend, running librespot twice and adding the stop command to stop mpd playing.
But I couldn't get it to work on my main listening system. 
I can't test right now, because the latest volumio update has locked me out and I don't have the time to reflash. But if your version works, my wife (and so I) will be very pleased.

Does librespot wait until all commands of the script are executed?
because the volumio stop command on the command line takes a while to execute.

Btw do you consider this to be the successor of your other plugin, or are you planning to develop them
both?
spotify-connect-web has some advantages above librespot, it has seamless playback. where librespot stops after every track leaving a silence. and it can be controlled with http commands.

**Comment by balbuze** [comment]
Hi!
Not sure yet that volspotconnect2 will replace volspotconnect. As you said, some features are missing. But dev are workking on it. But as it exists, the plugin works. And can swap from a device to an other. The only prob is that it is slow, about 8 sec... And I have a plan to manage several account in a different way, with only one device seenable (instead of two). To be follow.
A tip for you, the ontop and onstart command must be in absolute path. Have a look in what I have done.

**Comment by cortegedusage** [comment]
Thanks for the tip I will surely look into your code.



2017-01-26 21:12 GMT+01:00 balbuze <notifications@github.com>:
