### ISSUE TITLE
volspotconnect2 needs an updated librespot

### ISSUE THREAD

**Issue by leafy7382** [balbuze/volumio-plugins#169]
New update on the Spotify side seems to cause crashes and this fixes it. https://github.com/librespot-org/librespot/pull/224

**Comment by martynwheeler** [comment]
How do we implement the fix on volumio?  Thanks

**Comment by balbuze** [comment]
Volumio uses a custom version of librespot.  We need to include last change and recompile the library.

**Comment by cortegedusage** [comment]
I'm quite sure ash and/or balbuze are aware of the new changes.
and when they find the time they will compile a new version of librespot
for volumio.
as a side note I believe they(librespot-org) are about to find a solution
upstream to avoid this sort of crashes...



2018-05-18 8:45 GMT+02:00 martynwheeler <notifications@github.com>:

**Comment by martynwheeler** [comment]
Thanks very much.  I'm glad it's a fixable problem.  Keep up the good work

**Comment by martynwheeler** [comment]
Does the other version of spotifyconnect also depend on librespot?  Or is it best just to wait until it is resolved?

Thanks

**Comment by ashthespy** [comment]
On it! ;-)

**Comment by ashthespy** [comment]
Anyone with a Mac client willing to test? https://github.com/balbuze/volumio-plugins/pull/171

**Comment by cortegedusage** [comment]
@ash not sure if it is related to Mac cliënt, was experiencing the same with android cliënt. Buy willing to test

**Comment by cortegedusage** [comment]
@ ash you made a type or you saved the armhf tar with one "-"  less...

Op 18 mei 2018 11:52 a.m. schreef "Ash" <notifications@github.com>:

Anyone with a Mac client willing to test? #171
<https://github.com/balbuze/volumio-plugins/pull/171>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/balbuze/volumio-plugins/issues/169#issuecomment-390156828>,
or mute the thread

**Comment by martynwheeler** [comment]
I had the issue on both windows and android clients

**Comment by martynwheeler** [comment]
I'm happy to test on android, windows and iOS (ipad) when I get home.

**Comment by cortegedusage** [comment]
thank you!!!!!!!

**Comment by martynwheeler** [comment]
I will test it out when I get home in an hour or so.

**Comment by martynwheeler** [comment]
All working from windows and android.

**Comment by rumil** [comment]
Working fine on MacOS and iOS as well

**Comment by jalindsley** [comment]
I'm new to Github, but I use Volumio with Spotify connect constantly.  I'm interested in learning how to apply this fix. Could someone please help to provide guidance?

**Comment by martynwheeler** [comment]
See the instructions here:
https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect2/readme.md

**Comment by jalindsley** [comment]
Thank you. Back in business.  Appreciate the help and the awesome development work!

**Comment by slyporks** [comment]
Hi, tried to install the new version last night with instructions here. 

https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect2/readme.md

When installing gets stuck at downloading plugin

_Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin_

Any suggestions? The uninstall seemed to have issues from the web GUI, any instructions on how to uninstall from the terminal window. 

Same behaviour on two raspberry pis, model B and 2 . 

/John.

**Comment by slyporks** [comment]
Hi, Not sure what the issues are with my trying to install manually. Will try a rebuild of volumio tomorrow and then try the manual install of volspotconnect2.

**Comment by slyporks** [comment]
Have installed a clean volumio on rpi b and 2, updated to latest firmware, then followed the instructions on https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect2/readme.md

both are failing after 

progress 70: 
installing dependencies. 

but do not have any further information on what the issue is.

**Comment by slyporks** [comment]
Ok, I seem to be sorted now :) . I like to change default passwords straight away when installing stuff, but I see that Volumio expects you to keep the same password if you are installing plugins, hmmmm. Reinstalled volumio again from stratch and the plugin installs with the default password. Guess thats why I couldn't uninstall the plugin cleanly either.

**Comment by twproject** [comment]
Hi All,
  i installed the latest version (from master repo) but from my android devices i cannot playback music

From my android 8 i don't see volumio on spotify app
From my wife android 6 i see volumio, i'm able to connect (it require some time) but it not play nothing due the song go to pause mode, if i try to play it don't start and remain in pause mode

**Comment by cortegedusage** [comment]
Just a thought @ashthespy and @balbuze 
As it is quite clear that updating the volumio plugins is quite hard for Volumio
wouldn't it be an idea to have the librespot binairy in a different repository, which then would
be downloaded by the plugin installer, this way minor changes in the spotify api. wouldn't need
all the hassle of putting a whole new version online which then need to be reviewed and pushed,
which is obviously taking to long. 
I believe Saiyato's snapcast plugin also always uses the latest snapcast release, or at least at one time it did...

anyway, like I said, just a thought.
cheers,

**Comment by ashthespy** [comment]
@cortegedusage  This is normally how it works - the `install.sh` pulls the latest binary from this repo. 
But my fraud OCD made me change the filename in the ìnstall.sh` so :roll_eyes:

**Comment by balbuze** [comment]
Yes. But this is the only way to change version number...

**Comment by cortegedusage** [comment]
@balbuze this would be true when you look at the package as a whole, but if you take librespot in a different repository you could number the versions of librespot over there.
But then again the easiest way would be to get back the upload capability within volumio.
Or to give every developper the right to push minor updates to Volumio. 
anyway, wrong board to discuss the issue of not pushing updates.
You guys are doing your work very well I might say...

Cheers!

**Comment by ashthespy** [comment]
@cortegedusage That indeed is the goal. I in fact started making a separate daemon in Rust (using librespot as a library) but got sidetracked with life ;-)  
But yes - I think it's smart to have separate version control for the daemon and the front end.

**Comment by felixlam9229** [comment]
made a clean volumio & installed dev spotify connect2 0.7.5 Yesterday night. All good ! my Android phones & Windows Spotify apps all can control & remote the volumio! However today i try it is no longer work.... Spotify apps doesnt sync with the Volumio.....

**Comment by balbuze** [comment]
Have you rebooted ?

**Comment by felixlam9229** [comment]
Yep... i did tried reboot & activate deactivate the plugin... no helps....

**Comment by felixlam9229** [comment]
i notice the Apps didnt get the information from the Volumio, as the song i playing with Web Ui not showing on my Phone apps.

**Comment by balbuze** [comment]
What do you mean by "as the song i playing with Web Ui not showing on my Phone apps."

**Comment by felixlam9229** [comment]
i mean the song information. Song name. As Yesterday i can see what song name being playing with Volumio. now just didnt show up what is playing.

**Comment by hebert99** [comment]
Hello,
I'm stuck at the same point as @slyporks :
<<<<<<<<<<<<<<<<<<<
This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin

<<<<<<<<<<<<<<<<
However, I did a successful installation of the plugin on another Pi3 Volumio a couple of weeks ago.
Seems that the server fails to respond, since I tried via web UI (for testing purposes) and the download progress gets stuck at the same 10%.
Any hint?

**Comment by hebert99** [comment]
Hi, it's me again.
Read issue # 176 and found the solution. Thanks @manin22 for the hint.

"Root cause:
User mistake ;-) The issue was caused by my first failed plugin installation running as the user root. It created the temp. directory /tmp/plugins without write access to anyone else:
drwxr-xr-x 2 root root 40 Jun 4 17:22 plugins
and didn't clean it at the end because of interruption. Due to that, it broke the new correct installation. So, not only the file /tmp/plugins/volspotconnect2.zip should be removed, but whole directory. After rmdir all works like a charm!"

I didn't need to reinstall volumio. Just removing /tmp/plugins as a root user worked for me, letting the installation process to create it as a normal user.
Thanks!
