### ISSUE TITLE
Empty media library after installing brutefir3 plugin

### ISSUE THREAD

**Issue by hoernix** [balbuze/volumio-plugins#270]
Hi,
I use volumio v2.773 on RPI3B+ with hifiberry digi+ pro and music files on a NAS.
When I install brutefir plugin from May 12th (as the latest version won't work with current publicly available volumio version) my NAS media library is empty and cannot be recreated/refreshed.
I cannot play files even if I select them by browsing the directory tree directly.

When I uninstall brutefir plugin and reboot, the library is still empty but I can fresh it.

Please find logs here: http://logs.volumio.org/volumio/3xjETlh.html

Is this the same issue as in #255?

Which plugin version do you recommend to use with volumio 2.773?

Regards
Markus

**Comment by balbuze** [comment]
hi!
I suggest you to test with a previous version: [plugin](https://github.com/balbuze/volumio-plugins/commit/49c13c6ea062fdbffbc85b5184513d5d80f7e071#diff-bdde518dae721ee32999fc9b7b7d54b9)
as there is still some problem...

**Comment by ogroot** [comment]
Had this similar problem with Brutefir. And was able to create a 'workaround'.
See my solution: [https://forum.volumio.org/music-library-empty-after-reboot-raspberry-volumio-t14413.html]

**Comment by balbuze** [comment]
@ogroot : for info, with last version, volume mixer is properly displayed now in UI, but it requires Volumio >= 2.776
Curious to see how it behaves with your NAS problem...

**Comment by ogroot** [comment]
I will try this soon, when I have some time

**Comment by hoernix** [comment]
Thank you for the quick reply, but I get the same behavior with the plugin version you pointed me to, see http://logs.volumio.org/volumio/IAabYUA.html

@ogroot thank you for the workaround, I gave it a try but it didn't work

**Comment by balbuze** [comment]
I made a change in last version of the plugin to restart mpd. feel free to test with a dev version of volumio

**Comment by hoernix** [comment]
Thanks for providing a fix. I will see how to install a dev version, when I have some time.

**Comment by hoernix** [comment]
I retested the latest plugin version with volumio 2.77 but still get the same issue

**Comment by hoernix** [comment]
it's volumio 2.777

**Comment by balbuze** [comment]
Damn! can try "volumio vrestart" please via ssh?

**Comment by hoernix** [comment]
Tried volumio vrestart but got the same result. Logs: http://logs.volumio.org/volumio/RmPZURL.html
BTW it is not just that the music library is empty, it is also not possible to recreate it.

**Comment by balbuze** [comment]
Sorry for that. I pull out from dust a rpi2 and an i2s Dac. I expect the same behaviour. It will be easier if I could reproduce the issue...

**Comment by ictin** [comment]
I have a somewhat related issue, in the sense that I don't see the media library sometimes.
But this is due to the fact that volumio is losing the connection to mpd. Somehow after I install the DSP plugin, the mpd is starting to behave strangely.
First, is taking a long time to start, something like 1-2 minutes.
Then I can see a lot of connections in the mpd.log, sometimes over 50 connections (I modified the mpd.conf to get more than the default 20) until I get Max connections reached. And sometimes, I only get one connection to mpd, but then volumio is not connecting to mpd.

Without the DSP plugin everything is fine, but after I install it on a fresh volumio 2.779 install, even if I disable it or uninstall it, the mpd stays in this weird state.
My box is a tinkerboard.

**Comment by balbuze** [comment]
it is very weird as the plugin does not modifiy mpd.conf
Btw, can you try to modify /volumio/app/plugins/music_service/mpd/mpd.conf.tmpl and add # at the beginning of each following lines:
please make a copy in order to be able to restore. If it goes very wrong `volumio updater restorevolumio`
`
# Resource Limitations ########################################################
#connection_timeout             "60"
#max_connections                        "20"
#max_playlist_length            "81920"
#max_command_list_size          "81920"
#max_output_buffer_size         "81920"
###############################################################################`
Then save and do `volumio vrestart`
let me know

**Comment by hoernix** [comment]
FYI: I installed plugin v1.8.3 in volumio 2.779 and by some unknown magic everything worked after the initial restart. For now, I will just keep the system running and enjoy the music ;-)

**Comment by balbuze** [comment]
;-)

**Comment by ictin** [comment]
With that change to mpd.conf.tmpl, I have the same issue. It is somehow better as if I comment everything except max connections I don't get so often over 50 connection, I can see that some of them are closed. The only workaround was to put the mpd.conf.tmpl max connections to 1000. And this is working for 80% of the cases. I still got the slow start, but at least is working


Here is an example of the slow start. More that 2 minutes to start:

volumio  10226  0.0  0.0   1444   320 ?        S    19:19   0:00 /bin/sh -c /usr/bin/sudo /bin/systemctl restart mpd.service
root     10227  0.0  0.1   4400  2276 ?        S    19:19   0:00 /usr/bin/sudo /bin/systemctl restart mpd.service
root     10232  0.0  0.0   3308  1484 ?        S    19:19   0:00 /bin/systemctl restart mpd.service
volumio  10235  0.0  0.0   1444   368 ?        S    19:19   0:00 /bin/sh -c /usr/bin/sudo /bin/systemctl restart mpd.service
root     10241  0.0  0.1   4400  2296 ?        S    19:19   0:00 /usr/bin/sudo /bin/systemctl restart mpd.service
root     10248  0.0  0.0   3308  1448 ?        S    19:19   0:00 /bin/systemctl restart mpd.service
mpd      10255  1.4  1.1 146176 23744 ?        Dsl  19:19   0:01 /usr/bin/mpd --no-daemon
volumio  10372  0.0  0.0   2084   548 pts/0    S+   19:21   0:00 grep mpd

**Comment by ictin** [comment]
Hi,
I have some updates. It seems that the issue is the snd_aloop module. If I try to start it on my tinkerboard with /usr/bin/sudo /sbin/modprobe snd_aloop index=7 pcm_substreams=2 the mpd will not work anymore correctly.  I see this issue with may connections and the mpd is timing out most of the time at the start. I don't even need to select the output to the loopback. Just activating the snd_aloop will create this issue.

**Comment by balbuze** [comment]
What is the version of Volumio use use? What is your device?

**Comment by ictin** [comment]
My device is Asus tinkerboard and the volumio version was volumio 2.779

**Comment by hoernix** [comment]
why did you close this issue? was it fixed? or is this a "won't fix"? If that's the case, too bad as your brutefir plugin was the main reason I chose volumio. Guess I need to look somewhere else then ...

**Comment by balbuze** [comment]
hello ;-)
Now news for month = no more problem = no more issue...
If not the case, did test last version available?
I you really want to try something new : 
Remove the plugin reboot and set your DAC
Update volumio to last dev version
```
cd /volumio
git checkout tw/modular_alsa
volumio vrestart
```
and install this plugin : [brutefir modular_alsa](https://github.com/balbuze/volumio-plugins/raw/alsa_modular/plugins/audio_interface/brutefir3/brutefir.zip)
```
wget https://github.com/balbuze/volumio-plugins/raw/alsa_modular/plugins/audio_interface/brutefir3/brutefir.zip
mkdir ./brutefir
miniunzip brutefir.zip -d ./brutefir
cd ./brutefir
volumio plugin install
cd ..
rm -Rf brutefir*
```
let me know ;-)

**Comment by hoernix** [comment]
Hello, I was just waiting patiently for fix ;-). 
Today I updated to volumio 2.834 and installed DSP v1.8.9. Unfortunately after the recommended restart the system didn't startup. I was not able to login via ssh.
So now I'm going to test a restore ;-)

I will test the steps you recommended next weekend, when I find some time

Thank you

**Comment by balbuze** [comment]
Hi you're not lucky as there's no reason the plugin affect the system... Have you tried to unplug the device?

**Comment by hoernix** [comment]
Hi, it was bad luck, the SD card died :-(
Fresh install of volumio 2.834 and brutefir plugin 1.8.9,
after `volumio plugin install` the script prints two times "Installation wird abgeschlossen" but does not exit. 
Pressed Ctrl C after 5 min
Activated Plugin via UI and reboot, after restart media library is empty.

Anything I can do to help you fix this issue?

**Comment by balbuze** [comment]
>  after `volumio plugin install` the script prints two times "Installation wird abgeschlossen" but does not exit.

yes this a bug in volumio ;-) you have to enable the plugin in UI
You can try the other plugin (see above) using the new modular_alsa
