### ISSUE TITLE
Unable to update plugin

### ISSUE THREAD

**Issue by ashthespy** [balbuze/volumio-plugins#6]
I just attempted to update to the new version 1.3.9 of the plugin on a pizero with volumio 2.031, and ended up with this:
````
Downloading plugin at http://127.0.0.1:3000/plugin-serve/volspotconnect_update.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/volspotconnect_update.zip
Creating folder on disk
Unpacking plugin
Checking for duplicate plugin
The following error occurred when installing the plugin: Error
````

Following which, the webui crashed, and now I only have SSH access, even after a reboot.

**Comment by balbuze** [comment]
I don't see the relationship between plugin and webUI. But anyway try 
ssh sudo rm -Rf /data/plugins/music_service/volspotconnect . Atfer in /data/configuration/plugins.json remove lines about volspotconnect (or even the file if you have no other plugin) and restart volumio : killall node. Could we continue here : https://github.com/balbuze/volumio-plugins/issues ? Thanks !
You may have to reboot if you have some error in removing files due to access right
and let me know.
I have to go now, next time tomorow (but I'll have a look before)

**Comment by balbuze** [comment]
Was it working before the update ? The last mod was to support mixer name with spaces in name.

**Comment by ashthespy** [comment]
Was working with no mixer (pizero + i2s Dac with software mixer) 
However, I still can't access the webUI. I just removed the plugin completely
````
sudo rm -Rf /data/plugins/music_service/volspotconnect
nano /data/configuration/plugins.json
````
removed volspotconnect entries, followed by a `killall node` and `shutdown -r`

**Comment by balbuze** [comment]
hi!
I think I understood what happened when desinstalling : due to some wrong access right on some folder in the plugin, uninstallation failed. The plugin is partially removed. When Volumio restarts, it try to launch the plugin but of course it fails and prevent volumio to starts. I'm working on that point.
