### ISSUE TITLE
Playback crashes for some songs

### ISSUE THREAD

**Issue by nbonamy** [balbuze/volumio-plugins#66]
Hello,

I have successfully setup volspotconnect2 and played some songs.

But it seems to crash on *some* songs. For instance on "Dealing on the Boulevard" from Lou Reed (spotify:album:3502jry0dmHTGRMuEj0gMp, https://open.spotify.com/embed/album/3502jry0dmHTGRMuEj0gMp), 1st song plays OK but 2nd song crashes with this in the logs :

Jul 09 06:46:00 volumio volumio[10964]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WireError("invalid value for enum: 12")', /checkout/src/libcore/result.rs:859
Jul 09 06:46:00 volumio volumio[10964]: note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build info from logs
Jul 09 06:47:34 volumio volumio[11669]: INFO:librespot: librespot 2154964 (2017-06-15). Built on 2017-06-18.

Any idea?

Thanks for the great stuff!

**Comment by balbuze** [comment]
Hi, you're right, some songs of this album kills librespot. Please can you report it in the librespot issue on github : https://github.com/plietar/librespot/issues/206 it seems this issue is known.

**Comment by volumiouser1234** [comment]
Hello,

I have actually the same problem since today.
I fixed some not working titles by playing the song from the source and not from my own playlist.
Here is the error code:

`Jul 09 15:38:12 volumio volumio[908]: info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
Jul 09 15:38:14 volumio volumio[1512]: INFO:librespot::session: Connecting to AP "lon2-accesspoint-a9.ap.spotify.com:4070"
Jul 09 15:38:15 volumio volumio[1512]: thread 'main' panicked at 'Authentication failed', /build/arm-unknown-linux-gnueabihf/release/build/librespot-eec8b364835af423/out/lib.rs:365
Jul 09 15:38:15 volumio volumio[1512]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jul 09 15:38:15 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jul 09 15:38:15 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Jul 09 15:38:16 volumio volumio[908]: info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
Jul 09 15:38:17 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Jul 09 15:38:17 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Jul 09 15:38:17 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Jul 09 15:38:17 volumio systemd[1]: Started Volspotconnect2 Daemon.
Jul 09 15:38:17 volumio volumio[1531]: INFO:librespot: librespot 6f24e3b (2017-05-15). Built on 2017-05-18.
Jul 09 15:38:17 volumio volumio[1531]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
Jul 09 15:38:17 volumio volumio[1531]: INFO:librespot::session: Connecting to AP "lon3-accesspoint-a23.ap.spotify.com:4070"
Jul 09 15:38:18 volumio volumio[1531]: INFO:librespot::session: Authenticated as "myname" !
Jul 09 15:38:18 volumio volumio[1531]: INFO:librespot::audio_backend::alsa: Using alsa sink
Jul 09 15:38:18 volumio volumio[1531]: INFO:librespot::session: Country: "DE"
Jul 09 15:38:20 volumio volumio[908]: info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
Jul 09 15:38:23 volumio volumio[1531]: INFO:librespot::player: Loading track "Nummer 1"
Jul 09 15:38:24 volumio volumio[908]: info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
Jul 09 15:38:25 volumio volumio[1531]: INFO:librespot::player: Track "Nummer 1" loaded
Jul 09 15:38:25 volumio kernel: pcm512x 1-004d: No SCLK, using BCLK: -2`

All titles worked perfectly and I enjoyed this tool until today

**Comment by daniellhotka** [comment]
Apparently Librespot has been fixed with the [latest commit](https://github.com/plietar/librespot/commit/aa86ebf549d6bb9937dcc3d7a54bd39f9e21defd)

**Comment by balbuze** [comment]
Yep! I'm going to compile it asap ;-)

**Comment by balbuze** [comment]
I uploaded a new version with the last version of librespot. Works for me.
x86 not done yet, as it fails to compil.

**Comment by volumiouser1234** [comment]
It works perfect, great work.
Thanks alot.

**Comment by nbonamy** [comment]
Just when I wanted to test, https://github.com/balbuze/volumio-plugins/issues/68 happens... I must be doomed :)

**Comment by balbuze** [comment]
I have compiled a new librespot. But problem are still here... need to check if I done something wrong

**Comment by balbuze** [comment]
The weird thing is that on one of my device, it still work with the previous version (the one on my github repo)

**Comment by cortegedusage** [comment]
Are you compiling from plietar?
Because There is a pull request with the new system information string.
See
https://github.com/plietar/librespot/pull/218

Maybe compile his PR.
https://github.com/fabian-z/librespot

Im not able to do it myself so cant check if this one is working.


Op 13 jul. 2017 9:04 p.m. schreef "balbuze" <notifications@github.com>:

**Comment by balbuze** [comment]
Ok I think I found the error... Compiling it now... Be back when ok ;-)

**Comment by balbuze** [comment]
@cortegedusage : yes this what I use. I also adjust the volume to avoid it to be 100%

**Comment by cortegedusage** [comment]
Great! Thanks for the effort!

Op 13 jul. 2017 9:40 p.m. schreef "balbuze" <notifications@github.com>:

**Comment by balbuze** [comment]
After three built, it still not working : can connect with no problem to spotify, but crach when starting to play...
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329

**Comment by balbuze** [comment]
have a look here https://github.com/balbuze/volumio-plugins/issues/68

**Comment by nbonamy** [comment]
Everything works fine! Thanks so much 👍
