### ISSUE TITLE
pushState messages are not emitted

### ISSUE THREAD

**Issue by tim-felix-lange** [balbuze/volumio-plugins#83]
As noticed by @lgroeb in [Issue #4 of AmpSwitch](https://github.com/tim-felix-lange/volumio-plugins/issues/4) plugin, volspotconnect2 does not emit pushState messages, preventing a proper interaction with other plugins like AmpSwitch. It would be very helpful, if volspotconnect2 would properly comply with the [Volumio architecture](https://volumio.github.io/docs/Development_How_To/System_Architecture.html).

**Comment by balbuze** [comment]
You're right. But I'm not sure how it could be implemented with librespot even if this is something I planned to do for a long time. If you can/want to help I'll be glad.

**Comment by lgroeb** [comment]
Hi, I really would like to help but I do not have the coding skills, sorry :-(


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: balbuze <notifications@github.com> 
Datum: 15.09.17  16:48  (GMT+01:00) 
An: balbuze/volumio-plugins <volumio-plugins@noreply.github.com> 
Cc: lgroeb <christian.legl@web.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [balbuze/volumio-plugins] pushState messages are not emitted
&nbsp; (#83) 

You're right. But I'm not sure how it could be implemented with librespot even if this is something I planned to do for a long time. If you can/want to help I'll be glad.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/balbuze/volumio-plugins","title":"balbuze/volumio-plugins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/balbuze/volumio-plugins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@balbuze in #83: You're right. But I'm not sure how it could be implemented with librespot even if this is something I planned to do for a long time. If you can/want to help I'll be glad."}],"action":{"name":"View Issue","url":"https://github.com/balbuze/volumio-plugins/issues/83#issuecomment-329804330"}}}

**Comment by tim-felix-lange** [comment]
I'm not a Spotify user, so I actually didn't even notice myself, as mentioned. I tried looking for a documentation, but let's say it too generous. So without any idea what librespot is doing and can be doing, I see no real hope that I can be of any help.

**Comment by balbuze** [comment]
solved with volspotconnect...
