### ISSUE TITLE
"brutefir failed to start, please check your config"

### ISSUE THREAD

**Issue by kayue** [balbuze/volumio-plugins#86]
I am using the brutefir plugin, but keep getting "brutefir failed to start, please check your config" message even all the advance settings is off, only using the flat preset.

I'm using USB output.

**Comment by balbuze** [comment]
Hi,
there is no "off " advanced settings. Even if you don't change anything, some default values are set. This values should work with most of DAC, but not always. Try to change the output format, most of dac doesn't support 24 bits. Play with this settings as I can't determine your hardware capabilities. 
In a console you can also try "brutefir /data/configuration/miscellanea/brutefir/volumio-brutefir-config" most of time the message will indicate you if the problem comes from input or output.

**Comment by kayue** [comment]
@balbuze Thank you for the tips, will try it out later!

**Comment by kayue** [comment]
@balbuze I have spotted few issues in my config related to sample format and filter format. (And submitted a PR in https://github.com/balbuze/volumio-plugins/pull/87)

Now I am stuck in `Too many blocks in coeff 0.` error. I looked into the source code but don't understand. Can you help?

```
BruteFIR v1.0m (November 2013)                                (c) Anders Torger

Internal resolution is 64 bit floating point.
Creating 4 FFTW plans of size 65536...finished.
Loading 4 coefficient sets...Too many blocks in coeff 0.
```

I am using NuPrime DAC-9

**Comment by balbuze** [comment]
Try to increase number of partition >8

**Comment by kayue** [comment]
@balbuze Thanks, it did fixed this specific error. 

I am still trying sample output one by one.. 😢

**Comment by kayue** [comment]
@balbuze End up using "S32_LE" as sample format.

To help others, I would like to post my working config:

- Left/right filter: flat.wav
- Filter format: S32_LE
- Number of partition: 8
- Input format: S16_LE
- Output format: S32_LE

My Pi 3 is USB outputting to NuPrime DAC-9. 
I did hear some noise after enabling the plugin, maybe processing power is not enough.

**Comment by balbuze** [comment]
I don't remember when I generated the filter flat, but if you don't use the same settings than the filter, it may work but you'll get a poor sound quality... Demo filters are just here to check everything is ok, not to improve the quality....
